---
updates:
  - commit-message:
      include: scope
      prefix: github-actions
    directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - commit-message:
      include: scope
      prefix: gomod
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: daily
version: 2
